// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzppfzCJZk4O8XRmQjarqvG0pAxm32Y3o',
    appId: '1:178880749588:android:a4bb22ed8cd5b550964701',
    messagingSenderId: '178880749588',
    projectId: 'gcm-study-bode',
    storageBucket: 'gcm-study-bode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0BvPUffwYbIgHoEMbpEreW-0Yj8LzKj8',
    appId: '1:178880749588:ios:4bf19db01a5c781a964701',
    messagingSenderId: '178880749588',
    projectId: 'gcm-study-bode',
    storageBucket: 'gcm-study-bode.firebasestorage.app',
    iosBundleId: 'com.example.gcmStudy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBHidFzDgO5Fv6UhVFZz_p7Yleqz2NLY',
    appId: '1:178880749588:web:c3c43375d0fffd3b964701',
    messagingSenderId: '178880749588',
    projectId: 'gcm-study-bode',
    authDomain: 'gcm-study-bode.firebaseapp.com',
    storageBucket: 'gcm-study-bode.firebasestorage.app',
    measurementId: 'G-71QCDGQ5KE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0BvPUffwYbIgHoEMbpEreW-0Yj8LzKj8',
    appId: '1:178880749588:ios:4bf19db01a5c781a964701',
    messagingSenderId: '178880749588',
    projectId: 'gcm-study-bode',
    storageBucket: 'gcm-study-bode.firebasestorage.app',
    iosBundleId: 'com.example.gcmStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBHidFzDgO5Fv6UhVFZz_p7Yleqz2NLY',
    appId: '1:178880749588:web:7e59948128365ae4964701',
    messagingSenderId: '178880749588',
    projectId: 'gcm-study-bode',
    authDomain: 'gcm-study-bode.firebaseapp.com',
    storageBucket: 'gcm-study-bode.firebasestorage.app',
    measurementId: 'G-272S2X3D05',
  );

}